In [1]:
import numpy as np

In [2]:
5/2

2.5

In [3]:
# Create array
arr1 = np.array([[1,2,3],[8,9,10]])

#Show
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [5]:
#Arithmetic operations with scalars on array
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.125     , 0.11111111, 0.1       ]])

In [6]:
#Exponential operation
arr1 ** 3

array([[   1,    8,   27],
       [ 512,  729, 1000]], dtype=int32)