In [1]:
import numpy as np

In [2]:
#Create array - 50 Lines
arr = np.arange(50).reshape((10,5))

#Show
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [3]:
#Lets transpose the Data
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [10]:
# Taking dot product of matrices (Dot product of two arrays. Specifically, If both a and b are 1-D arrays, it is inner product of vectors)
np.dot(arr.T,arr)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [11]:
# For 3D matrix - Shape the matrix with 5 deep and 5 by 2 arrays
arr3d = np.arange(50).reshape((5,5,2))

#Show
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [12]:
#We can also transpose a 3d matrix
#the first column will be all the zero, zero of every individual slice.
#So if we look back at the original 3D array matrix, we had a zero, a ten,
#a 20, a 30, a 40 as the first row, and first column indexed value.

arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [13]:
# If you need to get more specific use swapaxes (function is used to interchange two axes of an array)
arr = np.array([[1,2,3]])

#Show 
arr

array([[1, 2, 3]])

In [9]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])