In [2]:
import numpy as np

In [6]:
#List
my_list1 = [1,2,3,4]

In [7]:
#Array
my_array1 = np.array(my_list1)

In [11]:
#Call the array
my_array1

array([1, 2, 3, 4])

In [12]:
#Another List
my_list2 = [11,22,33,44]

In [14]:
#Add both toghether
my_lists = [my_array1,my_list2]

In [16]:
#Make Multi-dimensional array or a matrix
my_array2 = np.array(my_lists)

In [17]:
#Call the array
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [18]:
#Lets get the size of the array
my_array2.shape

(2, 4)

In [19]:
#Find out the data type of the array
my_array2.dtype

dtype('int32')

In [20]:
#Matrix
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
#Identiy Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
#An array we are going to use a lot of
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
#A bit more specific
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])