In [1]:
# Universal functions perform operations on all elements in an array
import numpy as np

In [2]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)

A

array([-0.38549354, -0.17020008,  1.02625031, -0.46167215,  0.82303086,
        1.14852833, -0.81114242, -0.16596457, -0.17748801, -0.24435143])

In [6]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([-0.8677201 , -1.79731803, -0.92785508, -1.30884994,  0.04335486,
       -0.61913107,  0.37178911, -0.51947592, -0.33417058, -0.55358486])

In [7]:
#Addition
np.add(A,B)

array([-1.25321364, -1.96751811,  0.09839522, -1.77052208,  0.86638573,
        0.52939726, -0.4393533 , -0.68544049, -0.51165859, -0.79793629])

In [8]:
#Finding max or min between two arrays
np.maximum(A,B)

array([-0.38549354, -0.17020008,  1.02625031, -0.46167215,  0.82303086,
        1.14852833,  0.37178911, -0.16596457, -0.17748801, -0.24435143])

In [9]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True